/* similar to program 90 only where the container class can be assigned 
to work to manage the event*/


import java.applet.*;
import java.awt.*;	//Color,Button classes in this package

import java.awt.event.*;	//ActionEvent and ActionListener

/*<applet code="Prog91.class" width="500" height="500"></applet>*/

public class Prog91 extends Applet implements ActionListener
{
	Button btnred,btnblue;
	
	public void init()
	{
		//create objects of button
		
		btnred = new Button("Red");	//"Red" is caption of button
		btnblue = new Button("Blue");
		
		//add button to applet interface
		add(btnred);
		add(btnblue);
		
		//delegate the events generated by buttons

		btnred.addActionListener(this);
		btnblue.addActionListener(this);
	}
	/* the listener object class has to be inner class(nested) so that it can 
	access the outer class members*/
		
	public void actionPerformed(ActionEvent ae)
	{
		//check which button is clicked
		if(ae.getSource() == btnred)	
			setBackground(Color.RED);
		else
			setBackground(Color.BLUE);
	}
}
