//an eg. of scrollbars
//Design 3 horizontal scrollbars which if manupilated, will alter the background
//color of applet

import java.applet.*;
import java.awt.*;
import java.awt.event.*;

/*<applet code="Prog94.class" width="500" height="500"></applet>*/

public class Prog94 extends Applet implements AdjustmentListener
{
	Scrollbar hsbr,hsbg,hsbb;
	
	public void init()
	{
		hsbr = new Scrollbar(Scrollbar.HORIZONTAL, 0,1,0,256);
		//orientation, others default ,incr ,min,max+1
		//as constant  as int value    value
	
		hsbg = new Scrollbar(Scrollbar.HORIZONTAL, 0,1,0,256);
		hsbb = new Scrollbar(Scrollbar.HORIZONTAL, 0,1,0,256);
		
		setLayout(null);
		
		hsbr.setBounds(150,105,250,30);
		hsbg.setBounds(150,240,250,30);
		hsbb.setBounds(150,315,250,30);				
		
		add(hsbr);
		add(hsbg);
		add(hsbb);
		
		setBackground(new Color(0,0,0));
		//as default value the thumb is to extreme left
		
		hsbr.addAdjustmentListener(this);
		hsbg.addAdjustmentListener(this);
		hsbb.addAdjustmentListener(this);				
		
	}
	
	public void adjustmentValueChanged(AdjustmentEvent ae)
	{
		//the getValue() of scrollbar gives the current value
		//generated by scrollbar
		
		int r = hsbr.getValue();
		int g = hsbg.getValue();
		int b = hsbb.getValue();
		
		setBackground(new Color(r,g,b));	
	}
}








